# Generated by Django 5.2.1 on 2025-06-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bino nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('budget', models.BigIntegerField(verbose_name='Byudjet (so‘m)')),
                ('start', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('pending', 'Rejalashtirilgan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('canceled', 'Bekor qilingan')], default='pending', max_length=50, verbose_name='Holat')),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat (Region)')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar (City)')),
                ('street', models.CharField(max_length=200, verbose_name='Ko‘cha (Street)')),
                ('destination', models.TextField(verbose_name='Mo‘ljal (Destination)')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['region', 'city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, help_text='MP4 format tavsiya etiladi', null=True, upload_to='media/videos/', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media fayllar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.PositiveIntegerField(verbose_name='Xonalar soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narx (so‘m)')),
            ],
            options={
                'verbose_name': 'Narx',
                'verbose_name_plural': 'Narxlar',
                'ordering': ['rooms'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(verbose_name='Qavat')),
                ('rooms', models.PositiveIntegerField(verbose_name='Xonalar soni')),
                ('price', models.BigIntegerField(verbose_name='Narx (so‘m)')),
                ('count', models.PositiveIntegerField(verbose_name='Donasi (soni)')),
                ('area', models.FloatField(verbose_name='Maydoni (m²)')),
                ('status', models.CharField(choices=[('available', 'Bo‘sh'), ('sold', 'Sotilgan'), ('reserved', 'Band qilingan')], default='available', max_length=50, verbose_name='Holat')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balkon mavjudmi')),
                ('orientation', models.CharField(choices=[('north', 'Shimol'), ('south', 'Janub'), ('east', 'Sharq'), ('west', 'G‘arb')], max_length=50, verbose_name='Yo‘nalish')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='main.building', verbose_name='Bino (loyiha)')),
            ],
            options={
                'verbose_name': 'Xonadon',
                'verbose_name_plural': 'Xonadonlar',
                'ordering': ['project', 'floor', 'rooms'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Manzil'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material nomi')),
                ('unit', models.CharField(max_length=50, verbose_name='O‘lchov birligi')),
                ('count', models.PositiveIntegerField(verbose_name='Qoldiq soni')),
                ('total_count', models.PositiveIntegerField(verbose_name='Umumiy soni')),
                ('company', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.building', verbose_name='Tegishli bino')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['name'],
            },
        ),
    ]
