# Generated by Django 5.2.1 on 2025-06-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flats/images/', verbose_name='Asosiy rasm'),
        ),
    ]
