# Generated by Django 5.2.1 on 2025-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_flat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='orientation',
            field=models.CharField(choices=[('north', 'Shimol'), ('north_east', 'Shimol-Sharq'), ('east', 'Sharq'), ('south_east', 'Janub-Sharq'), ('south', 'Janub'), ('south_west', 'Janub-G‘arb'), ('west', 'G‘arb'), ('north_west', 'Shimol-G‘arb')], max_length=20, verbose_name='Yo‘nalish'),
        ),
    ]
