# Generated by Django 5.2.1 on 2025-06-01 04:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt')),
                ('role', models.CharField(max_length=200, verbose_name='Rol nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'ordering': ['role'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='user_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='O‘rta ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ish boshlagan sana')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ishdan ketgan sana')),
                ('about_skill', models.TextField(verbose_name="Ko'nikmalar haqida")),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oylik maosh')),
                ('working_hours_per_week', models.FloatField(default=0, verbose_name='Haftalik ish soatlari')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='user.employee', verbose_name='Xodim')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='user.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Xodim roli',
                'verbose_name_plural': 'Xodim rollari',
                'unique_together': {('employee', 'role')},
            },
        ),
    ]
