# Generated by Django 5.2.1 on 2025-06-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_client_clientinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinteraction',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employee', verbose_name="Mas'ul operator"),
        ),
    ]
