# Generated by Django 5.2.1 on 2025-06-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_clientinteraction_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinteraction',
            name='user',
        ),
    ]
