# Generated by Django 5.2.1 on 2025-06-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_clientinteraction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
    ]
